### ISSUE TITLE
Pass the sidebar menu and routes to the vuex store

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#101]
## Feature request

Hello, the menu and routes are displayed in the vuex store to have there the status of the data by window, process, smart browser and reports, to show in the horizontal submenu other items corresponding to the selected one

The ZK customer currently handles a tree with no limit on the number of levels, however as the trend of current applications this is not implemented.
![Peek 18-11-2019 17-37](https://user-images.githubusercontent.com/20288327/69097329-b9c8ba00-0a2c-11ea-8329-ba742325aa03.gif)

In the Vue client for ADempiere the main menu is managed at two levels and the elements that have superior levels are visualized from mosaic views to access them or from a window, process/report, or smart browser view are available from the relationship in the context menu. 
![Peek 18-11-2019 17-36](https://user-images.githubusercontent.com/20288327/69097351-c3522200-0a2c-11ea-9fe7-3059d564f5ee.gif)
![Peek 18-11-2019 17-43](https://user-images.githubusercontent.com/20288327/69097353-c5b47c00-0a2c-11ea-8855-1ab1df2ba05d.gif)

**Comment by EdwinBetanc0urt** [comment]
The ZK customer currently handles a tree with no limit on the number of levels, however as the trend of current applications this is not implemented.
![Peek 18-11-2019 17-37](https://user-images.githubusercontent.com/20288327/69097329-b9c8ba00-0a2c-11ea-8329-ba742325aa03.gif)


In the Vue client for ADempiere the main menu is managed at two levels and the elements that have superior levels are visualized from mosaic views to access them or from a window, process/report, or smart browser view are available from the relationship in the context menu. 
![Peek 18-11-2019 17-36](https://user-images.githubusercontent.com/20288327/69097351-c3522200-0a2c-11ea-9fe7-3059d564f5ee.gif)
![Peek 18-11-2019 17-43](https://user-images.githubusercontent.com/20288327/69097353-c5b47c00-0a2c-11ea-8855-1ab1df2ba05d.gif)
