### ISSUE TITLE
Pagination not working on POS Product Search Panel

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1020]
#### Steps to reproduce

1. Open POS
2. Select an Open Order
3. Click on the POS Product Search Panel (icon: magnifying glass)
4. Click on the panel's pagination numbers
5. The display doesn't change

#### Screenshot or Gif
![20210806_POS_Search_Product_Pagination](https://user-images.githubusercontent.com/1789408/128545443-25558476-b172-4ebb-88bf-d6a4a2fbe890.gif)

#### Expected behavior
It is expected that the panel displays the next page with the corresponding products, or the page number selected with the corresponding products.
Neither of them happens.

#### Other relevant information
- Your OS: Kubuntu 20.04
- Web Browser: Firefox
- Node.js version: -
- adempiere-vue version: 5.0

**Comment by elsiosanchez** [comment]
Greetings! @marcalwestf  this error is on hold by backend
