### ISSUE TITLE
Logout Dialog Too Big

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1034]
## Feature request
When a user wants to log out, the dialog that is displayed is too big. 
It shulld be displayed proportional to the monitor.

#### Gif
![image](https://user-images.githubusercontent.com/1789408/128660112-6c7b770f-47bb-418b-ba9e-ea2260e058a7.png)

**Comment by elsiosanchez** [comment]
Greetings @marcalwestf this issue is awaiting confirmation by Pull Request. #1036
