### ISSUE TITLE
Quantities of POS lines incremented with click

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1035]
## Bug report
The product quantities of the POS lines can be increased/decreased only by typing in the quantity.
Same occurs with price.
Additionally, the lines accept negative quantities.
#### Steps to reproduce

1. Open POS, add a product.
2. At the end of the line, click on the _Edit_ button (the green one).
3. Then click this time on the quantity field.
4. Try to increase or decrease the quantity by clicking on the side arrows.
5. When clicking on the arrows, the focus on the quantity gets lost. The only way to change the quantity is by typing it in via keyboard.
6. Type in a negative number. The negative number is accepted. This can also be seen on the footer.

#### Screenshot or Gif
![20210809_POS_Increment_quantity](https://user-images.githubusercontent.com/1789408/128719298-03b1035a-74f2-434a-945b-7abc501bfed5.gif)
![image](https://user-images.githubusercontent.com/1789408/128719940-25ac1fa7-47ce-4867-aa04-c581fd487e55.png)

#### Expected behavior
An easy way for the user (for example with a touchscreen) to increase or decrease the quantity by clicking on the side arrows.
Usually on POS the quantities are whole numbers (integers), so increasing and decreasing by one should be alright.
The quantity should not be decreased below zero.

Also, negative quantities should not be allowed (also in the "normal" standard Sales Order Line).

**Comment by elsiosanchez** [comment]
Greetings @marcalwestf  this issue is awaiting confirmation by Pull Request. #1050
