### ISSUE TITLE
Footer Display When no Order active

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1038]
#### Describe the solution you'd like
If there is no Order loaded on the POS, the footer (bottom right) should display clearly that there is no sensible data to display.
More precisely, the _Date_ field, as well as quantities and amounts should have a content that signals "here is no content" like twice a hyphen (--) or nothing, like the fields _Order_ _Seller_ and _Type_.

This way the user knows unequivocally that she must create a new Order.

When a new Order is created, the quantities and amounts should display 0, as it is the real value of the existing Order.

Here how it looks right now when no Order is active:
![Selection_023](https://user-images.githubusercontent.com/1789408/128895420-028ee6a9-73dc-4e6c-a1cf-016c596dd15b.png)

**Comment by elsiosanchez** [comment]
Greetings @marcalwestf thanks for the feedback this topic is awaiting confirmation by Pull Request. #1053
