### ISSUE TITLE
New Order button after new Order has been created

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1039]
## Bug report
The _New Order_ button (of color blue on the upper right corner) still appears after a new order has been created.
#### Steps to reproduce

1. Open the POS
2. Press  _New Order_ button -> a new Order is created.
3. The button _New Order_ is still there. Pressing it has no consequences, or so it seems.

#### Screenshot or Gif
![Selection_024](https://user-images.githubusercontent.com/1789408/128896561-4d586f9b-ba1a-4b73-8691-7fc8519274d8.png)

#### Expected behavior
After a new Order has been created either the  _New Order_ button should disappear or it should create a new Order when pressed.
The following situations should be mastered: 

1. The user pushes the  _New Order_ button several times.
2. The user is working on an Order, but for some reason, another customer must be served first. In cases like this, it should be possible to create a new Order, finish it and come back to the original order (for example in Sales Order/Load Last Order).
3. When should be permitted to create a new Order? Perhaps after adding at least one product to an Order? 
4. How prevent users from creating many unused Orders?
4. If the button disappears after creating a new Order, how should a new Order be created?
5. etc.

**Comment by elsiosanchez** [comment]
Greetings! @marcalwestf  the button is not hidden as it is a quick way to create a new order without opening the POS options panel.
