### ISSUE TITLE
After Running Cache Reset, Focus always goes to Dashboard, instead of last Tab or (ideally) last active Tab

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1042]
## Bug report
After executing the _Cache Reset_ process, the application focus goes back to the _Dashboard_.
**This is not a real bug**, but an important user experience.
On ZK, it goes back to the last tab.
#### Steps to reproduce

1. Open many windows or forms (e.g. _Sales Order_ and _POS_).
2. Look for process Cache Reset and execute it.
3. The application focus is now Dashboard, instead of the POS form.

#### Screenshot or Gif
![20210811_Cache_Reset](https://user-images.githubusercontent.com/1789408/129058944-75d8723e-7555-4533-8678-a901a74ef252.gif)

#### Expected behavior
Ideally, after executing the _Cache Reset_ process, the user expects the application focus to be on the last window or for it was before calling it. 

If this is too complicated, at least, the last tab (in this case the POS) should get the focus. This is better than seeing the Dashboard. This is the present behavior on ZK.
![image](https://user-images.githubusercontent.com/1789408/129059475-ad402fa3-a256-4ab8-8876-43a135cbbf05.png)

**Comment by elsiosanchez** [comment]
Greetings! @marcalwestf I created a pull request solving this issue [1268](https://github.com/adempiere/adempiere-vue/pull/1268) please could you check
