### ISSUE TITLE
[Bug Report] Reverse the Sales Transaccion 

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere-vue#1044]
## Bug report

The Process "Reverse the Sales Transaction" from the POS doesn't work. When you run it, ir show the follow Error: 
**Error de Validación Factura Pagado**

![Screenshot_2021-08-11_15-33-10](https://user-images.githubusercontent.com/31936815/129084166-39a3b69e-3e8f-4fa8-abb1-c1fbe662548a.png)

![Revertir transacción de Ventas Error](https://user-images.githubusercontent.com/31936815/129084179-dafafff1-110c-488d-a955-00aaf89a4279.gif)

I try from ZK and it works OK

![OK desde ZK](https://user-images.githubusercontent.com/31936815/129084735-342169bf-b86b-4fb0-95a5-609bdf630bcc.png)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: DEMO

**Comment by niclopup** [comment]
related to https://github.com/adempiere/adempiere-vue/issues/595

**Comment by elsiosanchez** [comment]
Greetings! @niclopup this error is on hold by backend

**Comment by niclopup** [comment]
@yamelsenih o @elsiosanchez how are you? 
Is this functionality ready to test? i am trying yo generate a Return form the POS but the action don't do anything
![Devolución no permite seleccionar](https://user-images.githubusercontent.com/31936815/134076613-22dc5d50-7d99-40ba-9ebb-85da95cdafa8.gif)

**Comment by rcapecce** [comment]
I'm testing this functionality but it is missing to set a required field.

I have my adempiere-vue (develop) setup pointing to Erpya endpoints  and get the next error message.
![Peek 13-10-2021 18-31](https://user-images.githubusercontent.com/14218144/137216016-501de11b-f100-455c-a819-d68b4446e03c.gif)

This was the request:
Endpoint: `https://api.erpya.com/api/adempiere/common/api/process?token=0f30454d-cbcd-4c97-8e2d-9b5f62190f49&language=es`
Body: `https://api.erpya.com/api/adempiere/common/api/process?token=0f30454d-cbcd-4c97-8e2d-9b5f62190f49&language=es`
Response: `{"code":200,"result":{"uuid":"","instance_uuid":"c4cc266b-f043-40f3-93f8-521bc4494574","is_error":true,"summary":"C_BPartner_ID is mandatory.","result_table_name":"","is_processing":false,"last_run":1634161083000,"logs_list":[],"parameters":{}}}`

**Comment by elsiosanchez** [comment]
Greetings! @rcapecce  The error is returning in the response.
