### ISSUE TITLE
[Bug Report] Can't Find the "Change Document Type" Process in POS

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere-vue#1045]
## Bug report

I couldnt try because i didnt find the process in the new POS

How does it works?

related to https://github.com/adempiere/adempiere-vue/issues/595

**Comment by marcalwestf** [comment]
hi @niclopup  as far as I have found, in order to process the Order you 

1. Click on the blue arrow (with the symbol ">") left to the product lines:
![image](https://user-images.githubusercontent.com/1789408/129099312-f13e7899-cf0a-4e4e-9835-9fab28c89a28.png)

2. Then you click on Sales Order:
![image](https://user-images.githubusercontent.com/1789408/129099519-a08240e7-d52b-4243-a9ea-226192447d48.png)

3. Change Document Type seems not to be implemented:
![image](https://user-images.githubusercontent.com/1789408/129099975-34ee5f8b-0694-4949-8979-b9739af80350.png)


You have to get used to it. I had also the same difficulties with Vue finding how to toggle between grid and document mode in windows.

**Comment by elsiosanchez** [comment]
Greetings! @niclopup  In the point of sale terminal, the document type assignment tab has been added to associate there the types of documents with which the terminal will work. 

1. Document Type Assignment Tab
![image](https://user-images.githubusercontent.com/45974454/129101551-cd45eac7-3b78-4777-b4ec-099ef6b70387.png)

![image](https://user-images.githubusercontent.com/45974454/129101671-f08979a7-af57-4f6a-b367-a5162d4e3ad6.png)

2. If you have more than one document type assigned in the document type assignment tab, the ADempiere-Vue interface shows you the field and allows you to change the document type. 

![image](https://user-images.githubusercontent.com/45974454/129102243-81c27042-5a9c-4fef-95da-a8f14af0ade6.png)

**Comment by niclopup** [comment]
Hi @elsiosanchez thanks for your answer!!
I define 2 Documents in "Caja 20" but i still don't see the option to change the Document Type.

![image](https://user-images.githubusercontent.com/31936815/129105347-83e844d5-4675-4116-acf6-363f4e1b5a4e.png)


![Tipo de Documento POS](https://user-images.githubusercontent.com/31936815/129105423-38d5ba9b-7592-46e6-9d83-9933a22123d0.gif)

**Comment by marcalwestf** [comment]
@elsiosanchez I can confirm @niclopup 's case: with the latest commit, I also cannot see the option you showed.
Perhaps a commit missing?
![image](https://user-images.githubusercontent.com/1789408/129113333-e51e0cc9-d3b2-49b3-9e8d-203781019db5.png)

**Comment by elsiosanchez** [comment]
Hello very good morning @marcalwestf  and @niclopup   I hope you are well, with respect to the types of documents for the point of sale the following configuration must be respected:

- Each POS terminal must have associated a base document type, which would be the default document type which at the time of working with the POS this comes out in the first instance. To associate the type of document, it must be done under the parent window of the "POS Terminal" in the "Type of Document" field.

- If this terminal wishes to work with another type of document, these types of documents must be associated to the POS terminal with which it is working in the "Assignment of Document Types" tab in the "POS Terminal" window.

Based on the above, this can be clearly seen with the POS terminals called "Point of Sale (VES)" and "Point of Sale (USD)".


![image](https://user-images.githubusercontent.com/45974454/129200211-2eced5e2-7d86-4a9b-a869-b48a1a8b38da.png)

**Comment by niclopup** [comment]
Thanks @elsiosanchez !
Now i can see the option also in the POS 20 as i define it.

![image](https://user-images.githubusercontent.com/31936815/129203440-07320efc-6fd4-4196-b405-ce952c264304.png)


Perhaps that it was necessary to reset the app? I already tried by reset Cache but it didn't work yesterday.

for me, we can close this issue!

**Comment by EdwinBetanc0urt** [comment]
Greetings  @marcalwestf @niclopup, the `Cache Reset` process only affects the backend, what is already loaded in the client like windows, processes, smart browser, most of the lists, ..., we store them in the vuex store to avoid too many requests to the server, so after executing the restart cache process, you must reload the browser tab (`ctrl + r`) to make requests to the server and render the new changes in the vue client.

**Comment by yamelsenih** [comment]
Hey.... Thanks for all.. just a little comment, is nice wait for confirm a issue before close it
