### ISSUE TITLE
[Bug Report] Create Business Partner Location from POS not easy

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere-vue#1046]
## Bug report
When you try to define the Location of the New Business Partner, if the resolution of the screen leave the Location POP-UP lower of the view, yo cant press "OK" to create the Business Partner. 

If you minimize the zoom you can but its not easy 

![Creación Cliente desde POS](https://user-images.githubusercontent.com/31936815/129085512-034ffd81-4c47-46ff-94bf-042e852fba53.gif)

Related to https://github.com/adempiere/adempiere-vue/issues/596

**Comment by elsiosanchez** [comment]
Greetings @niclopup  this issue is awaiting confirmation by Pull Request.  #1051

**Comment by niclopup** [comment]
Great!
