### ISSUE TITLE
An Order in a status "completed" should not offer lines to be edited nor deleted

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1055]
## Bug report
When in a _completed_ Order, the Orderline buttons for editing and deleting should be disabled.

#### Steps to reproduce

1. Open a completed Order in the POS
2. Select any line and click on the _Edit_ (green) icon -> the discount, quantity and price can at first be modified, but then there is a weird message.
3. Select any line and click on the _Delete_ (red) icon -> a weird messase pops up.
4. Same applies to Document Type.
5. The POS Terminal  can be modified. If a different value is selected, the present Order is discarded and a new one is displayed!

#### Screenshot or Gif
![20210812_modify_completed_orderlines](https://user-images.githubusercontent.com/1789408/129274057-7e0e9a5f-d4f3-4a7c-adf9-d984ae264893.gif)
![20210812_delete_completed_orderlines](https://user-images.githubusercontent.com/1789408/129274197-aa518bef-7006-4726-922e-6dc808eac417.gif)
![20210812_select_Warehouse_on_Completed_Orders](https://user-images.githubusercontent.com/1789408/129275084-7f54839c-3ba6-41a4-acb4-22e03c5daba9.gif)
![20210812_change_Terminal_on_completed_Orders](https://user-images.githubusercontent.com/1789408/129275881-3501c495-0347-4d46-bb45-d14a5de5fb3b.gif)

#### Expected behavior
None of them should be activated when the Order is in the completed status.

**Comment by elsiosanchez** [comment]
Greetings @marcalwestf this issue is awaiting confirmation by Pull Request. #1057
