### ISSUE TITLE
Status and New Order buttons same dimensions and font size

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1056]
## Feature request
The Buttons for Statement end New Order should have same dimensions and same font size:
![image](https://user-images.githubusercontent.com/1789408/129279496-0f077a97-e625-4575-894e-e4769a501484.png)

Moreover, they should arrange orderly in different situations:
![image](https://user-images.githubusercontent.com/1789408/129279683-a4760149-35f3-4392-90d0-bae4707c5603.png)

**Comment by elsiosanchez** [comment]
Greetings! @yamelsenih I created a pull request solving this issue #1118

**Comment by elsiosanchez** [comment]
Greetings! @marcalwestf please could you check
