### ISSUE TITLE
Product Search window ordered by Value or by Name

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1058]
## Feature request
It would be desirable if the _Product Search_ window could be ordered by either Value or Name.
The **minimal functionality** would be to have an order, be it Value or Name. 

Right now, it doesn't seem to be ordered either by Value nor Name:
![image](https://user-images.githubusercontent.com/1789408/129415213-952ad7f5-d1cb-4f9e-a6e4-aae880b71ee8.png)

#### Describe the solution you'd like
Ideally the user would tip on the header ("Key" or "Product")  and get the list ordered in this manner, with every tipping reversing the order.

If this is not possible, the  _Product Search_ window should at least implement an order; the order should be configurable perhaps on the POS Terminal, because the customers may have different wishes. But then, it would be less work to program the order altogether.

Another point would be to get rid of the _Price List_. This is a known fact, already displayed on the POS (bottom left) and redundant here.
Better would it be for example the _**Quantity on Hand**_ on the warehouse.

**Comment by elsiosanchez** [comment]
Greetings! @yamelsenih I created a pull request solving this issue #1225  please could you check
