### ISSUE TITLE
Product Search combo box ordered by value

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1059]
## Feature request
The _Product Search_ combo box should be ordered by value.
Right now, the products are shown in an unordered manner.
The list displays first the value, then the name of every product; that is why the suggestion to order by value.
![image](https://user-images.githubusercontent.com/1789408/129418346-394612a1-2502-47b1-b582-b529b4e03aa8.png)

#### Describe the solution you'd like
1. Order the list by value
2. Reduce the line separation; the present separation is too large.
3. Delimit the products either by drawing a line between products or by a larger separation then between product and product description. Problem of the latter solution would be the cost is space.
4. Think of getting rid of the product description altogether. It is debatable whether at the moment of looking for a product, the description is of any use. If it is, it could be configurable in the POS Terminal.

**Comment by elsiosanchez** [comment]
Greetings! @yamelsenih I created a pull request solving this issue #1225 please could you check
