### ISSUE TITLE
Browser 404 error when selecting an entry from the path

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1060]
## Bug report
Browser 404 error when selecting an entry from the path
#### Steps to reproduce

1. Open the POS form
2. Move cursor to the object path on the upper left corner of the POS and position it on the tree dots between dashes 
(Dashboard /.../ POS)
3. A list of three items is displayed.
4. Select (=click on) _Quote-to-Invoice_.
5. A 404 Browser error is shown.

#### Screenshot or Gif
![20210813_Browser_404_error](https://user-images.githubusercontent.com/1789408/129421815-60bcda2a-9e86-43f5-9140-71f4821f3b2c.gif)

**Comment by elsiosanchez** [comment]
Greetings! @marcalwestf I created a pull request solving this issue [1267](https://github.com/adempiere/adempiere-vue/pull/1267) please could you check
