### ISSUE TITLE
Changing Price List not possible on POS

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1065]
## Bug report
Changing Price List not possible on POS
#### Steps to reproduce

1. Assing additional Price Lists to a _POS Terminal_
2. Open a POS and create a new Order
3. Try to change the Price List by clicking on the default Price List.
4. Nothing but an almost unnoticeable artifact is displayed to select.
5. Same happens when  a new Order is not created.

#### Screenshot or Gif
![image](https://user-images.githubusercontent.com/1789408/129594521-f02098bd-85b1-4438-bad9-c0501447eefb.png)

![20200816_Change_POS_PriceList](https://user-images.githubusercontent.com/1789408/129594258-ad544a6c-18da-4e1c-94e0-626b47716388.gif)

#### Expected behavior
The Price Lists configured should be displayed.

**Comment by marcalwestf** [comment]
@elsiosanchez  one question: what happens when the user changes the price list and there are already products in the Order?
Are the products deleted and the user should add them again, or are the prices adapted?
Thanks

**Comment by yamelsenih** [comment]
Hi @marcalwestf the behavios is the same that the old POS, when you change the price list all order lines are recalculated and if a product not exist in the new price list it will be deleted from order


Best regards
