### ISSUE TITLE
Search Product window: several issues

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1076]
#### Steps to reproduce
- When  the _Search Product_ window is opened and a search text is typed in so that there is no match, non-matching messages are generated until the user closes the window. If the  _Search Product_ window is closed after a long time, a seeming endless amount of messages are displayed for the whole session, not only for the POS, but even after logout.
- Same happens when there are timeouts.
- When the _Search Product_ window is opened, the last search is displayed.
- When the user clicks on the search text area, the cursor set on the place where the mouse where when the click was issued.
#### Screenshot or Gif
![20210817_POS_SearchProduct_error](https://user-images.githubusercontent.com/1789408/129799814-f25ed3a8-c82e-4c2f-abc7-055b593731af.gif)
![20210817_POS_SearchProduct_error_2](https://user-images.githubusercontent.com/1789408/129800039-c2985ca8-25a2-4d29-b890-c15751d3a95d.gif)

#### Expected behavior
- The messages and timeouts should be caught and displayed in such a manner that they do not hinder the operation of the POS.
I assume this is not only related to the POS, but also to windows, reports, etc.
- Perhaps should messages not be displayed in a row, but on stack, so that if there are several messages, the user only sees one.
- On the other side, if there are hundreds of messages, something with the operation went wrong and is has to be interrupted.
- When the _Search Product_ window is opened, I would expect a new search, not the last one.
- When the user clicks on the search text area, if there is an existing text, it should be selected, so it is replaced by the eventual input. Now it has to be deleted. Almost always, a new search is desired, not a search based on the last one.

**Comment by elsiosanchez** [comment]
Greetings! @marcalwestf I created a pull request solving this issue #1217
