### ISSUE TITLE
Quick Point of Sales Options: should collapse after selection

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1077]
## Feature request
After a selection has been made on the _Quick Point of Sales Options_, it should collapse
#### Describe the solution you'd like
- The _Quick Point of Sales Options_ is used mostly to execute an action; afterwards the user would like to continue working on the POS Order.
- In order to achieve this, the user must as of now close the _Quick Point of Sales Options_ manually.
- Better would it be if the system closes it so the user doesn't have to do it.

How it works today:
![20210817_Quick Point_of_Sales_Options](https://user-images.githubusercontent.com/1789408/129802597-4b3cecef-267e-4189-bd12-da1af309ac0e.gif)

**Comment by yamelsenih** [comment]
Very nice it. @elsiosanchez please add it to changes
