### ISSUE TITLE
Tipping on a Sales Order Line should open the line editor

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere-vue#1093]
## Feature request
In the POS, when clicking or tipping an order line, the order line editor should open.
#### Describe the solution you'd like
Right now, to edit an order line on the POS, you must click the edit button (the green one):
![image](https://user-images.githubusercontent.com/1789408/130294089-a4248faf-1da8-44ef-ac00-356cf6223ced.png)
![image](https://user-images.githubusercontent.com/1789408/130294124-7edff89c-ef4a-4cf1-b611-9bc0d73a2f23.png)

For a better user experience, it should suffice to tip on the line to open the editor.

**Comment by elsiosanchez** [comment]
Greetings! @marcalwestf  I created a proposal pull request according to your suggestion.
