### ISSUE TITLE
Add support for advanced search

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#110]
In the zk the advanced search is managed as a modal search.
![Peek 18-11-2019 18-32](https://user-images.githubusercontent.com/20288327/69100230-1a5af580-0a33-11ea-8897-b9e0a8db6746.gif)

In the new interface of vue for ADempiere the advanced search is part of the data table, accessible to the user in a fast way.
![Peek 18-11-2019 18-44](https://user-images.githubusercontent.com/20288327/69100417-83db0400-0a33-11ea-8016-4c7baba604a7.gif)

![Peek 18-11-2019 18-43](https://user-images.githubusercontent.com/20288327/69100316-4aa29400-0a33-11ea-9df4-b60d264b8356.gif)

**Comment by yamelsenih** [comment]
Hi @EdwinBetanc0urt is nice to have a operator (optional) for advanced query
