### ISSUE TITLE
Add support to sequence tabs.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#111]
Sequence tabs are handled as follows from the ZK client for ADempiere:
![Peek 18-11-2019 18-57](https://user-images.githubusercontent.com/20288327/69101192-58f1af80-0a35-11ea-99fd-d40ce9736c57.gif)

This type of sequence tabs are not currently handled, however element has standard components that resemble the way of working to apply the sequences.
https://element.eleme.io/#/en-US/component/transfer#customizable

![Peek 18-11-2019 18-56](https://user-images.githubusercontent.com/20288327/69101123-247df380-0a35-11ea-9737-ea49b8242da1.gif)

**Comment by yamelsenih** [comment]
Hi @EdwinBetanc0urt maybe can use this tool from original repository also:
![Current ogv](https://user-images.githubusercontent.com/2333092/69133788-d85e9d80-0a8c-11ea-871c-ad36a497957f.gif)
