### ISSUE TITLE
Support to Recent Items

### ISSUE THREAD

**Issue by elsiosanchez** [adempiere/adempiere-vue#119]
Hi, the traditional Recent Items container was changed using a web user interface kit ([Element-UI](https://element.eleme.cn/2.7/#/en-US))

- **ADempirer**
![zk](https://user-images.githubusercontent.com/45974454/69166584-d7982c80-0ac9-11ea-8e36-8f2bb7155c34.gif)
-**[Element-UI](https://element.eleme.cn/2.7/#/en-US/component/timeline)**
![element](https://user-images.githubusercontent.com/45974454/69166761-25149980-0aca-11ea-8e93-fe33323ce0e5.gif)
- **ADempirer-Vue**
![vue](https://user-images.githubusercontent.com/45974454/69166794-3362b580-0aca-11ea-84bd-72929e50d37d.gif)

**Comment by EdwinBetanc0urt** [comment]
This is working

![recent-item](https://user-images.githubusercontent.com/20288327/112574547-e630db00-8dc4-11eb-8417-2fb601f48468.gif)
