### ISSUE TITLE
Migrate Tabs

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#12]
It is proposed to migrate the tabs, changing the vertical design to the left for a horizontal design at the top. It is currently displayed as follows in the ZK client:

Viewing from a desktop screen:
![Screenshot_20191118_093720](https://user-images.githubusercontent.com/20288327/69058699-88c79580-09ea-11ea-8f81-334b9fa3f1a5.png)

Viewing from a mobile phone:
![Screenshot_20191118_095548](https://user-images.githubusercontent.com/20288327/69058705-89602c00-09ea-11ea-93d8-368c34f4a550.png)

The standard component of element-ui to use is named tab, type edge letter (https://element.eleme.io/#/en-US/component/tabs#border-card):
![screenshot-2018-12-28 componentes element](https://user-images.githubusercontent.com/20288327/50520503-1a5aab80-0a97-11e9-9e7d-9fccf12baf28.png)

This display of the new interface, are grouped the tabs with the same table name at the top and the other tabs at the bottom.

Viewing from a desktop screen:
![Screenshot_20191118_094341](https://user-images.githubusercontent.com/20288327/69058700-88c79580-09ea-11ea-9d60-a8681affe64a.png)

Viewing from a mobile device:
![Screenshot_20191118_094531](https://user-images.githubusercontent.com/20288327/69058702-88c79580-09ea-11ea-8d01-370fc9ea95f5.png)

**Comment by yamelsenih** [comment]
Hi @EdwinBetanc0urt please add a example gif or image
