### ISSUE TITLE
Support to print format selection

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#129]
Hello, currently in ADempiere, after generating a report, it allows you to change the print format as shown below.
**ADempiere**
![zk-print-format-selection](https://user-images.githubusercontent.com/23490674/69176164-9872d700-0adb-11ea-84a4-8852a0d4166c.gif)

This feature is to migrate to the new UI developed under the javascript framework, Vuejs

**Comment by EdwinBetanc0urt** [comment]
fixes with https://github.com/adempiere/adempiere-vue/pull/695
