### ISSUE TITLE
[Bug Report] Organization empty when you log in

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere-vue#1295]
## Bug report
Once you log in in VUE, the field of Organization is empty, this should be like this or it would be better if it define automatically one of the Organization that the user has acces?

![image](https://user-images.githubusercontent.com/31936815/138870684-35c69126-fcb5-4da6-b5b9-d101b39b0476.png)

If its better to have an organization defined, wich Organization it should define? now there is not a check of "is Default"

#### Steps to reproduce

1. log In in VUE with "demo" user
2. See the information of the Context by click in the right logo of AD

**Comment by EdwinBetanc0urt** [comment]
Greetings @niclopup ,  it is indeed an error, if there is no default organization, you should choose the first organization from the list that you have access to at login
