### ISSUE TITLE
Allow to remove column of "Converted" in POS

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere-vue#1359]
Now the "Terminal POS" allow to choose if you want to see the "Tax" column or the "Discount" column by the check "Show Discount" or "show Tax".

It could be good idea to add the same option to the Column of "Converted" because no always it will be necessary to show it.

An example of how it is now the "Terminal POS" with this checks.

![image](https://user-images.githubusercontent.com/31936815/141301687-5465d48d-952e-4266-8ab3-bf039a87c51a.png)

The idea is to add a new check to show or hide the column of "Converted" in the POS

**Comment by rcapecce** [comment]
The functionality has been validated with Elsio, the "Converted Amount" field appears when the "DisplayCurrency_ID" field appears set in the POS Terminal, if this field is not established, the column disappears from the list of added items.
