### ISSUE TITLE
[Bug Report] Method not found

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere-vue#1477]
## Method not found
When a Release Order is pressed, a error is throwed

#### Steps to reproduce

1. Go to Point of Sales
2. Create a new Order
3. Press button **Release Order**
4. See the error

#### Screenshot or Gif（截图或动态图）
![Screenshot_20220128_113917](https://user-images.githubusercontent.com/2333092/151576838-1a326aa0-fc4b-4b72-81de-b57e1523dddd.png)

#### Expected behavior
Just release the order for take it from other seller

#### Other relevant information
- Your OS: Linux
- Web Browser: Chrome
- Node.js version: latest
- adempiere-vue version: latest from develop

#### Additional context
Here a log:

```
index.vue?6ced:878 Error Hold Order Method not found: data.Store/ReleaseOrder. Code: undefined
```

**Comment by elsiosanchez** [comment]
Please add in the Issued the role with which you are entering to duplicate the error
I just did it with the Advisor role and it works satisfactorily

![asespr](https://user-images.githubusercontent.com/45974454/151583140-93673893-918a-4e23-9e22-8df2de2993d5.gif)

**Comment by yamelsenih** [comment]
A bad deploy for service, sorry
