### ISSUE TITLE
[Bug Report] Mandatiry fields don't allows search orders

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere-vue#1478]
## Search Orders is not allowed
When you try search a order, is mandatory fill two fields.

#### Steps to reproduce

1. Open Point of Sales
2. Go to Find Orders
3. See the error

#### Screenshot or Gif（截图或动态图）
![Screenshot_20220128_114737](https://user-images.githubusercontent.com/2333092/151578046-291f6f8a-b5dc-4fbb-af7f-8b61a06fb616.png)

#### Expected behavior
This window should not have a mandatory field instead

#### Other relevant information
- Your OS: Linux
- Web Browser: Chome
- Node.js version: Latest
- adempiere-vue version: Latest from develop

#### Additional context
This behavior is introduced from last merge

**Comment by elsiosanchez** [comment]
Greetings, this problem is solved in the next PR #1483
