### ISSUE TITLE
[Bug Report] Window: Table is very too long time to load

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere-vue#1714]
## Bug report
The left table take very too long time to show records, also this should have a loading component to show to user

#### Steps to reproduce

1. Open Product Group
2. Go to List Table
3. Press table button

#### Screenshot or Gif（截图或动态图）
![Tabla tarda demasiado en cargar](https://user-images.githubusercontent.com/2333092/160035228-7dfdb4fc-97f4-4f02-b275-20c1570fd091.gif)

**Comment by elsiosanchez** [comment]
Solved in the next PR [1732](https://github.com/adempiere/adempiere-vue/pull/1732)
