### ISSUE TITLE
[Bug Report] Window: Default values not set

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere-vue#1718]
## Bug report
The default value is not set for windows

#### Steps to reproduce

1. Go to Requisition
2. Press new
3. Fill all fields
4. See the Document Status field.... The error is that this field is mandatory, is read only and the default value showld be **Drafted** but is not setted

#### Screenshot or Gif（截图或动态图）
See the ZK
- Date
- Priority
- Document Status
![Valor por defecto en ventana ZK](https://user-images.githubusercontent.com/2333092/160037065-4bf0cb2c-c254-4b83-857c-ba5609d44ed0.gif)

See the Vue UI
![Valor por defecto en ventana UI](https://user-images.githubusercontent.com/2333092/160037078-605337cb-a031-4fed-980c-0722dda2eb56.gif)

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/161965412-41b0c4a2-67a5-4edb-b68f-b07ab85d5338.mp4



fixes https://github.com/adempiere/adempiere-vue/issues/1716
