### ISSUE TITLE
Unify popovers

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#190]
You must unify the two popover that are activated on the field when they have context information and zoom in.
![adempiere-vue-2-popover](https://user-images.githubusercontent.com/23490674/69961803-01e2e480-14e3-11ea-8b64-2b740d9798ab.png)

**Comment by elsiosanchez** [comment]
@yamelsenih please close this issue.

**Comment by EdwinBetanc0urt** [comment]
the popovers of the field options were unified with this PR
https://github.com/adempiere/adempiere-vue/pull/888 https://github.com/adempiere/adempiere-vue/pull/867
