### ISSUE TITLE
[Bug Report] Export zip text file void (no data)

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#241]
#### Steps to reproduce

1. Enter in any window.
2. Open table of records (left side).
3. In table menu, select _Export zip_ option.

#### Screenshot or Gif
![export-zip-void](https://user-images.githubusercontent.com/23490674/72822392-6bac7e80-3c48-11ea-9537-4a7470f6cabf.gif)

#### Expected behavior
If no table record is selected, there are 2 options:
1. Lock the option so that it cannot be executed.
2. Export all records in a file

#### Other relevant information
- Your OS: Kubuntu 19.04
- Node.js version: 12.13.1

**Comment by EdwinBetanc0urt** [comment]
@yamelsenih please close this issue.
