### ISSUE TITLE
[Bug Report] Error trying zoom in process from process activity

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#249]
#### Steps to reproduce

1. Execute a process.
2. Go to process activity.
3. Try to zoom in the process executed.

#### Screenshot or Gif（截图或动态图）
![zoom-from-process-activity](https://user-images.githubusercontent.com/23490674/72842961-f654a400-3c6f-11ea-97d6-7a9863e8ae07.gif)

#### Expected behavior
This action must open the process with the parameters that were executed.

#### Other relevant information
- Your OS: Kubuntu 19.04
- Node.js version: 12.13.1

**Comment by EdwinBetanc0urt** [comment]
This is working

![zoom-process](https://user-images.githubusercontent.com/20288327/112573161-1a56cc80-8dc2-11eb-8772-859260f7e871.gif)
