### ISSUE TITLE
[Bug Report] Bugfix changing report format after generate report.

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#257]
#### Steps to reproduce

1. Open report with more than one print format.
2. Execute report
3. After the report is generated, change print format.
4. Note that the print format does not change

#### Screenshot or Gif
![print-format](https://user-images.githubusercontent.com/23490674/72933253-c53fa680-3d37-11ea-843a-0b02e5117621.gif)

#### Expected behavior
The report should change according to the print format

#### Other relevant information
- Your OS: Kubuntu 19.04
- Node.js version: 12.13.1

**Comment by EdwinBetanc0urt** [comment]
fixes with https://github.com/adempiere/adempiere-vue/pull/695
