### ISSUE TITLE
[Bug Report] Why is response Content-Type 'application/grpc-web-text' is not supported

### ISSUE THREAD

**Issue by caiqfrog** [adempiere/adempiere-vue#295]
## Bug report

grpc server response Content-Type 'application/grpc-web-text' is not supported

#### Steps to reproduce

I release my vue client and proxy with nginx.
1. start adempiere-access-server, nginx proxy with grpcs://localhost:8989
2. open web and login, but it response Content-Type 'application/grpc-web-text' is not supported

#### Other relevant information
- Your OS: centos 7
- Node.js version: v10.15.0
- vue-element-admin version: 4.1.0

**Comment by EdwinBetanc0urt** [comment]
Greetings, @caiqfrog  you may indicate which version of nginx you are running the test on?

**Comment by yamelsenih** [comment]
Hi @caiqfrog maybe you have a wrong configutation for Nginx, I use https://github.com/erpcya/gRPC-Envoy-Proxy and is ok

**Comment by caiqfrog** [comment]
ok，I found grpc-web request‘s Content-Type=application/grpc-web+proto.
and view the grpc-java, it validate Content-Type by regex(application/grpc(+)?.*;), so illegal.
I use that to resolve it, application/grpc-web+proto body frame the same as application/grpc+proto:
```
grpc_pass grpcs://localhost:50051;
grpc_set_header Content-Type application/grpc+proto;
```
