### ISSUE TITLE
[Bug Report] No list option for Document Type in Sales Order Window

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#296]
#### Steps to reproduce

1. Open _Sales Order_ window.
2. Select **New Record** option in context menu.
3. Try to select a **Target Document Type**.

#### Screenshot or Gif
![no-list-option](https://user-images.githubusercontent.com/23490674/73660156-04da8c80-466e-11ea-8b3b-0d18bf67e6b3.gif)

#### Expected behavior
The available values to choose from in this field should appear, since it is a mandatory field

#### Other relevant information
- Your OS: Kubuntu 19.04
- Node.js version: 12.13.1

**Comment by EdwinBetanc0urt** [comment]
This is working

![target-document-type](https://user-images.githubusercontent.com/20288327/112573504-d1534800-8dc2-11eb-9b7c-0d6350dd0c82.gif)
