### ISSUE TITLE
Context variable

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#4]
handle context variables in the client based on session storage

**Comment by yamelsenih** [comment]
@EdwinBetanc0urt can you add more description or a image for it?

**Comment by elsiosanchez** [comment]
it was changed to Localstorage so that the data is still stored so that the window is changed or updated and the only way to delete the data is to indicate it

**Comment by EdwinBetanc0urt** [comment]
It will be handled in global objects with Vue.prototypes, so they can be accessed from any site in the app, and avoid conversion and call from localStorage or sessionStorage optimizing performance.

**Comment by EdwinBetanc0urt** [comment]
* **Global context variables.**
![context](https://user-images.githubusercontent.com/20288327/53020853-398a0f80-342e-11e9-8bfb-3402c68ba2d8.png)


* **Container context variables**, the Container is equivalent to window, report, smart browse, form and workflow, identified by the uuid, and with the values of the fields of the first subcontainer (tab).
![context containers](https://user-images.githubusercontent.com/20288327/53020854-398a0f80-342e-11e9-9919-f4663948d637.png)


* **Fields of the sub container.**
![context sub container](https://user-images.githubusercontent.com/20288327/53020856-398a0f80-342e-11e9-9f26-4c802c6c2c96.png)
