### ISSUE TITLE
Sopport Text Component

### ISSUE THREAD

**Issue by elsiosanchez** [adempiere/adempiere-vue#47]
Migration of the component input text using element and vuejs

![screenshot_20190109_115248](https://user-images.githubusercontent.com/45974454/50910957-3e0de200-1405-11e9-9d8c-9a442a27c97d.png)

The text field is currently displayed in the ZK client for ADempiere as follows
![Peek 18-11-2019 20-09](https://user-images.githubusercontent.com/20288327/69105053-9b6cb980-0a40-11ea-9453-c33809c8a5e0.gif)

Element standard text component
https://element.eleme.io/#/en-US/component/input#basic-usage
![Peek 18-11-2019 20-16](https://user-images.githubusercontent.com/20288327/69105064-9f98d700-0a40-11ea-8b6a-7c9529525993.gif)

Text component in the Vue client for ADempiere
![Peek 18-11-2019 20-11](https://user-images.githubusercontent.com/20288327/69105076-a3c4f480-0a40-11ea-9910-4689615cafc5.gif)

**Comment by elsiosanchez** [comment]
It is a base component of https://github.com/adempiere/adempiere-vue/issues/57

**Comment by EdwinBetanc0urt** [comment]
The text field is currently displayed in the ZK client for ADempiere as follows
![Peek 18-11-2019 20-09](https://user-images.githubusercontent.com/20288327/69105053-9b6cb980-0a40-11ea-9453-c33809c8a5e0.gif)

Element standard text component
https://element.eleme.io/#/en-US/component/input#basic-usage
![Peek 18-11-2019 20-16](https://user-images.githubusercontent.com/20288327/69105064-9f98d700-0a40-11ea-8b6a-7c9529525993.gif)

Text component in the Vue client for ADempiere
![Peek 18-11-2019 20-11](https://user-images.githubusercontent.com/20288327/69105076-a3c4f480-0a40-11ea-9910-4689615cafc5.gif)
