### ISSUE TITLE
[Bug Report] The last build based from develop branch not show button actions and the detail lines sales order window

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere-vue#525]
## Bug report

The last build based from develop branch not show the detail lines sales order window

#### Steps to reproduce

1. git clone https://github.com/adempiere/adempiere-vue.git
2. git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
3.  npm install 
audited 2159 packages in 12.948s

59 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

4.- npm audit fix
audited 2159 packages in 12.948s

59 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
e-Evolution@MacBook-Pro-de-Victor adempiere-vue % npm audit fix
up to date in 7.447s

59 packages are looking for funding
  run `npm fund` for details

fixed 0 of 2 vulnerabilities in 2159 scanned packages
  2 vulnerabilities required manual review and could not be updated

5- npm fund
adempiere-vue@4.2.1
├─┬ https://opencollective.com/babel
│ └── @babel/core@7.9.0, @babel/core@7.10.3
├─┬ https://tidelift.com/funding/github/npm/autoprefixer
│ └── autoprefixer@9.8.3
├─┬ https://github.com/chalk/chalk?sponsor=1
│ └── chalk@4.0.0
├─┬ https://opencollective.com/core-js
│ └── core-js@3.6.5, core-js-compat@3.6.5
├─┬ https://opencollective.com/eslint
│ └── eslint@6.8.0
├─┬ https://opencollective.com/husky
│ └── husky@4.2.5
├─┬ https://opencollective.com/lint-staged
│ └── lint-staged@10.2.0
├─┬ https://opencollective.com/webpack
│ └── sass-loader@8.0.2, webpack@4.43.0, schema-utils@2.7.0, terser-webpack-plugin@2.3.7, copy-webpack-plugin@5.1.1, css-loader@3.6.0
├─┬ https://github.com/sponsors/sindresorhus
│ └── screenfull@5.0.2, p-limit@2.3.0, make-dir@3.1.0, ansi-escapes@4.3.1, figures@3.2.0, type-fest@0.11.0, globals@12.4.0, cli-truncate@2.1.0, p-map@4.0.0, log-update@4.0.0, is-finite@1.1.0
├─┬ https://github.com/sponsors/isaacs
│ └── glob@7.1.6, rimraf@3.0.2
├─┬ https://github.com/sponsors/ljharb
│ └── resolve@1.17.0, has-symbols@1.0.1, util.promisify@1.0.1, es-abstract@1.17.6, object.getownpropertydescriptors@2.1.0, es-to-primitive@1.2.1, is-callable@1.2.0, is-regex@1.1.0, object-inspect@1.8.0, string.prototype.trimend@1.0.1, string.prototype.trimstart@1.0.1, is-date-object@1.0.2, is-symbol@1.0.3, deep-equal@1.1.1, object-is@1.1.2, regexp.prototype.flags@1.3.0, object.values@1.1.1
├─┬ https://tidelift.com/funding/github/npm/browserslist
│ └── browserslist@4.12.0
├─┬ https://github.com/avajs/find-cache-dir?sponsor=1
│ └── find-cache-dir@3.3.1
├─┬ https://github.com/sponsors/feross
│ └── safe-buffer@5.2.1, arch@2.1.2
├─┬ https://www.patreon.com/feross
│ └── safe-buffer@5.2.1, arch@2.1.2
├─┬ https://feross.org/support
│ └── safe-buffer@5.2.1, arch@2.1.2
├─┬ https://github.com/chalk/ansi-styles?sponsor=1
│ └── ansi-styles@4.2.1
├─┬ https://tidelift.com/funding/github/npm/postcss
│ └── postcss@7.0.32
├─┬ https://github.com/sponsors/wooorm
│ └── vendors@1.0.4
├─┬ https://tidelift.com/subscription/pkg/npm-loglevel?utm_medium=referral&utm_source=npm_fund
│ └── loglevel@1.6.8
├─┬ https://github.com/sponsors/RubenVerborgh
│ └── follow-redirects@1.12.1
├─┬ https://github.com/sponsors/jonschlinkert
│ └── picomatch@2.2.2
├─┬ https://github.com/sponsors/mysticatea
│ └── vue-eslint-parser@7.1.0
├─┬ https://github.com/sindresorhus/execa?sponsor=1
│ └── execa@4.0.2
├─┬ https://github.com/chalk/slice-ansi?sponsor=1
│ └── slice-ansi@4.0.0
└─┬ https://github.com/sponsors/gjtorikian/
  └── isbinaryfile@4.0.6

6.- npm run dev  
> adempiere-vue@4.2.1 dev /Users/e-Evolution/Develop/ADempiere/adempiere-vue
> vue-cli-service serve

 INFO  Starting development server...
40% building 154/188 modules 34 active /Users/e-Evolution/Develop/ADempiere/adempiere-vue/node_modules/sockjs-client/dist/sockjs.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
98% after emitting CopyPlugin

 DONE  Compiled successfully in 13498ms                                                                                                                                                                                     10:03:49 PM

  App running at:
  - Local:   http://localhost:9527/ 
  - Network: http://192.168.1.77:9527/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

7.-Login as GardenAdmin password GardenAdmin
8.- Go the Sales Order Window 

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/786968/85648689-f44fa080-b666-11ea-8289-7a239b95ffb8.png)

![image](https://user-images.githubusercontent.com/786968/85648741-15b08c80-b667-11ea-9fc7-f0036a5f5581.png)

![image](https://user-images.githubusercontent.com/786968/85649346-91f79f80-b668-11ea-855b-25299e92bc98.png)

![image](https://user-images.githubusercontent.com/786968/85649388-afc50480-b668-11ea-9afb-06ab649bbc4e.png)
#### Expected behavior
When a sales order is load the button actions should be show as the demo 

![image](https://user-images.githubusercontent.com/786968/85649162-ff570080-b667-11ea-8232-07ac14b9730f.png)

What is the problem ?

#### Other relevant information
- Your OS: MacOS
- Node.js version: v14.4.0
- vue-element-admin version: adempiere-vue@4.2.1

**Comment by yamelsenih** [comment]
This was fixed from latest version
