### ISSUE TITLE
[Question]Unable to login. An unexpected error has occurred, try again

### ISSUE THREAD

**Issue by mathewkaplos** [adempiere/adempiere-vue#528]
Am unable to connect to the Adempiere server.

I am using ADempiere 3.9.3 , and I have downloaded the latest  Adempiere gRPC server(rt-15.0).
So my question is: where and how do I link the ademiere vue project to my local adempiere server.

![login error](https://user-images.githubusercontent.com/12475545/90312548-07b41500-df0e-11ea-920c-5a9fd5db46cd.PNG)

**Comment by EdwinBetanc0urt** [comment]
Greetings @mathewkaplos , you must configure the proxy for the gRPC server to accept requests from the client in vue.js, here is the proxy repository we use https://github.com/erpcya/gRPC-Envoy-Proxy there are examples of how to use it with docker and docker-compose.

**Comment by mathewkaplos** [comment]
Thanks @EdwinBetanc0urt . Let me do that and I will give a feedback

**Comment by yamelsenih** [comment]
Hi everyone this was changed by proxy ADempiere api. You can see ti: https://github.com/adempiere/proxy-adempiere-api
Also all docker images are available here: https://hub.docker.com/u/erpya
