### ISSUE TITLE
Support to the Locator (Warehouse) component

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#62]
Hello, it is required to migrate the locator component, which shows a reference list, based on Vuejs and Element UI

**ADempiere**
![zk-locator](https://user-images.githubusercontent.com/23490674/69159217-eed11d00-0abd-11ea-960a-7f8f5c1914fc.gif)

**[Element UI]**(https://element.eleme.io/#/en-US/component/select)
![element-list](https://user-images.githubusercontent.com/23490674/69159291-10320900-0abe-11ea-9bbd-3a7042366234.gif)

**ADempiere Vue Desktop**
![Screenshot_20191119_111358](https://user-images.githubusercontent.com/23490674/69159353-29d35080-0abe-11ea-9ea7-75dd59b8ca7c.png)

**ADempiere Vue Mobile**
![Screenshot_20191119_111505](https://user-images.githubusercontent.com/23490674/69159393-3788d600-0abe-11ea-822d-dc65ff0d7282.png)

**Comment by yamelsenih** [comment]
Please add real lookup for Locator (Warehouse) component

**Comment by leonel1524** [comment]
**ADempiere**
![zk-locator](https://user-images.githubusercontent.com/23490674/69159217-eed11d00-0abd-11ea-960a-7f8f5c1914fc.gif)

**[Element UI]**(https://element.eleme.io/#/en-US/component/select)
![element-list](https://user-images.githubusercontent.com/23490674/69159291-10320900-0abe-11ea-9bbd-3a7042366234.gif)

**ADempiere Vue Desktop**
![Screenshot_20191119_111358](https://user-images.githubusercontent.com/23490674/69159353-29d35080-0abe-11ea-9ea7-75dd59b8ca7c.png)

**ADempiere Vue Mobile**
![Screenshot_20191119_111505](https://user-images.githubusercontent.com/23490674/69159393-3788d600-0abe-11ea-822d-dc65ff0d7282.png)

**Comment by yamelsenih** [comment]
@elsiosanchez
