### ISSUE TITLE
Support for number component

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#64]
Hello, it is required to migrate the ADempiere number component, based on Vuejs and Element UI
- **ADempiere**
![zk](https://user-images.githubusercontent.com/45974454/69094692-3e183e80-0a27-11ea-8fe3-e184183113fa.gif)

- **Element-UI**
https://element.eleme.cn/2.7/#/en-US/component/input-number
![element](https://user-images.githubusercontent.com/45974454/69094711-42dcf280-0a27-11ea-85e2-b3d113b2e2cc.gif)

- **ADempiere-Vue**
![numbervue](https://user-images.githubusercontent.com/45974454/69094729-48d2d380-0a27-11ea-946a-120cfd6413ba.gif)

- **ADempiere-Vue mode Mobile**
![numberMobil](https://user-images.githubusercontent.com/45974454/69094750-525c3b80-0a27-11ea-8fcb-57b8f28fe104.gif)

**Comment by elsiosanchez** [comment]
- **ADempiere**
![zk](https://user-images.githubusercontent.com/45974454/69094692-3e183e80-0a27-11ea-8fe3-e184183113fa.gif)

- **Element-UI**
https://element.eleme.cn/2.7/#/en-US/component/input-number
![element](https://user-images.githubusercontent.com/45974454/69094711-42dcf280-0a27-11ea-85e2-b3d113b2e2cc.gif)

- **ADempiere-Vue**
![numbervue](https://user-images.githubusercontent.com/45974454/69094729-48d2d380-0a27-11ea-946a-120cfd6413ba.gif)

- **ADempiere-Vue mode Mobile**
![numberMobil](https://user-images.githubusercontent.com/45974454/69094750-525c3b80-0a27-11ea-8fcb-57b8f28fe104.gif)

**Comment by EdwinBetanc0urt** [comment]
@yamelsenih This issue is duplicated in https://github.com/adempiere/adempiere-vue/issues/10, please close it.

**Comment by EdwinBetanc0urt** [comment]
duplicated https://github.com/adempiere/adempiere-vue/issues/10
