### ISSUE TITLE
Sequence  Tab

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere-vue#642]
Just a sequence tab support for windows
![Screenshot_20210311_173105](https://user-images.githubusercontent.com/2333092/110857729-97952400-828f-11eb-884d-a070dacb9f66.png)

**Comment by EdwinBetanc0urt** [comment]
![update sequence-error](https://user-images.githubusercontent.com/20288327/110875907-e2716480-82ac-11eb-9d23-0ed70be80d22.gif)

This is working, however, there are some incessant requests being made, as shown in the example:
In sequence of identifiers were `Name` (`SeqNo` 10) and Description (`SeqNo` 20).

`AD_Workbench_ID` was added at the beginning (SeqNo 10), reordering the sequence of the following fields: `Name` (`SeqNo` 20) and `Description` (`SeqNo` 30).

The affected fields are 3 in total, one added as identifier and two changed sequence.

The fourth request, belonging to the `UUID` column, is executed without fulfilling the condition of removing an identifier (which sets the `SeqNo` attribute to 0, and/or sets the IsIdentifier attribute to false):
```json
{
	"attributes": [
		{
			"key": "SeqNo",
			"value": 0
		}
	],
	"table_name": "AD_Column",
	"uuid": "8c24ed40-fb40-11e8-a479-7a0060f0aa01"
}
```
