### ISSUE TITLE
[Bug Report] Page 404 Selecting a first level summary menu from the breadcrumb

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#658]
#### Screenshot or Gif
![breadcrumb-error](https://user-images.githubusercontent.com/20288327/110720581-387ad500-81e5-11eb-988a-cccf1571f75b.gif)

#### Expected behavior
If any path is selected in the breadcrumb it should redirect to the selected path.

#### Other relevant information
- Your OS: Linux Mint 19.1 Cinnamon x64.
- Web Browser: Mozilla Firefox 85.0.
- Node.js version: 12.20.0.
- adempiere-vue version: 4.3.1.

#### Additional context
This only occurs with first level menu items, such as summary.

Perhaps it could be solved by encapsulating the routes (root) inside the `Layout` component that returns the method ![getRouteFromMenuItem](https://github.com/adempiere/adempiere-vue/blob/develop/src/router/modules/ADempiere/menu.js#L128) and the summary type routes with the `src/views/ADempiere/Summary` component (instead of the current `Layout`).

**Comment by elsiosanchez** [comment]
Greetings! @EdwinBetanc0urt   I created a pull request solving this issue [1267](https://github.com/adempiere/adempiere-vue/pull/1267) please could you check
