### ISSUE TITLE
[Feature Request] Support Field reference 

### ISSUE THREAD

**Issue by elsiosanchez** [adempiere/adempiere-vue#663]
## Feature request

Field preference support in ADempiere-Vue
Unlike the ZK interface in ADempiere-Vue you can open the reference popover in all fields.

### Referencia de Campo en la Interfaz ADempiere-ZK
![zk](https://user-images.githubusercontent.com/45974454/110875615-58c19700-82ac-11eb-98a8-a0bd2d1e4166.gif)
### Referencia de Campo en la Interfaz ADempiere-VUe
![preference](https://user-images.githubusercontent.com/45974454/110875631-61b26880-82ac-11eb-9f49-35d3b973e80a.gif)

#### Issues:
Fixes: #145

**Comment by EdwinBetanc0urt** [comment]
@elsiosanchez @yamelsenih Duplicate issue https://github.com/adempiere/adempiere-vue/issues/145
