### ISSUE TITLE
Users permission.

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#67]
Permission control is required to adapt the side menu to the role of the session, thus preventing roles from accessing tools that do not correspond to them.

**ADempiere**
![zk-change-role](https://user-images.githubusercontent.com/23490674/69096346-9dc41900-0a2a-11ea-8cce-fcd8c5537884.gif)

**ADempire Vue**
![permission](https://user-images.githubusercontent.com/23490674/69096374-ad436200-0a2a-11ea-9967-5cd03257dd84.gif)

https://element.eleme.cn/2.7/#/en-US/component/form

- **[Element-UI](https://element.eleme.cn/2.7/#/en-US/component/form)**
![element](https://user-images.githubusercontent.com/45974454/69150267-bb3ac680-0aae-11ea-89f3-d2c5bd3fd975.gif)

**Comment by yamelsenih** [comment]
Hi @leonel1524 where is element URL?

**Comment by elsiosanchez** [comment]
Hi @yamelsenih  
https://element.eleme.cn/2.7/#/en-US/component/form

- **[Element-UI](https://element.eleme.cn/2.7/#/en-US/component/form)**
![element](https://user-images.githubusercontent.com/45974454/69150267-bb3ac680-0aae-11ea-89f3-d2c5bd3fd975.gif)
