### ISSUE TITLE
API for queries with gRPC

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#71]
Through the implementation of gRPC using the library [@adempiere/grpc-dictionary-client](https://www.npmjs.com/package/@adempiere/grpc-dictionary-client) on the client, queries of objects and requests of their methods will be made.

**Comment by yamelsenih** [comment]
hey, as additional info it can consume the follow projects:
- [https://github.com/erpcya/gRPC-Dictionary-Client](https://github.com/erpcya/gRPC-Dictionary-Client)
- [https://github.com/erpcya/adempiere-gRPC-Server](https://github.com/erpcya/adempiere-gRPC-Server)
