### ISSUE TITLE
Add horizontal menu component

### ISSUE THREAD

**Issue by leonel1524** [adempiere/adempiere-vue#80]
You want to add a new feature which allows you to execute actions on the current tool (window, process, report, smart browser, etc.), open other tools that are related to this, etc.

**ADempiere**
The main idea is to change the keypad used in ADempiere to perform all the actions on a register or other actions to a practical component
![Screenshot_20191119_113004](https://user-images.githubusercontent.com/23490674/69160650-512b1d00-0ac0-11ea-84fc-a57b358b2aec.png)

[**Element-UI**](https://element.eleme.io/#/en-US/component/menu#top-bar)
![element-menu-horizontal](https://user-images.githubusercontent.com/23490674/69084223-29817980-0a1a-11ea-8f98-60c962b01b2c.gif)

**ADempiere Vue Desktop**
![Menu Horizontal](https://user-images.githubusercontent.com/23490674/69084309-5897eb00-0a1a-11ea-8ce1-e17054121e6e.gif)

**ADempiere Vue Mobile**
![adempiere-vue-mobile-menu-horizontal](https://user-images.githubusercontent.com/23490674/69084254-3dc57680-0a1a-11ea-9495-21a5844c346c.gif)

**Comment by yamelsenih** [comment]
Hi @leonel1524 where is Element URL? and old implementation?
