### ISSUE TITLE
Improve responsive design for mobile field groups 

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#87]
In ADempiere client ZK the setting does not have adjustment of the size of the group of fields in relation to the fields and the container.
![Peek 19-11-2019 09-46](https://user-images.githubusercontent.com/20288327/69151976-10c4a280-0ab2-11ea-91ad-173702fe3e82.gif)

In the client of Vue for ADempiere the groups of fields is placed in 1 column for the group without assignment, the groups of assigned fields are placed 2 columns if the size allows it, otherwise it takes 1 column.
![Peek 19-11-2019 09-48](https://user-images.githubusercontent.com/20288327/69152010-191cdd80-0ab2-11ea-8927-143d6e941fda.gif)
![Peek 19-11-2019 09-49](https://user-images.githubusercontent.com/20288327/69152015-1b7f3780-0ab2-11ea-90f8-49fd2a3fb231.gif)

Note: If the group of fields is 1 column (and the display size allows it) the columns for the fields that are within the group are 4, otherwise they are 2 columns for the fields within the group.

**Comment by EdwinBetanc0urt** [comment]
In ADempiere client ZK the setting does not have adjustment of the size of the group of fields in relation to the fields and the container.
![Peek 18-11-2019 14-17](https://user-images.githubusercontent.com/20288327/69079801-2766ed00-0a11-11ea-9dbb-5b04158a47d9.gif)


In the client of Vue for ADempiere the groups of fields is placed in 1 column for the group without assignment, the groups of assigned fields are placed 2 columns if the size allows it, otherwise it takes 1 column.
![Peek 18-11-2019 14-21](https://user-images.githubusercontent.com/20288327/69079812-2c2ba100-0a11-11ea-8595-a815fa1b55eb.gif)


Note: If the group of fields is 1 column (and the display size allows it) the columns for the fields that are within the group are 4, otherwise they are 2 columns for the fields within the group.

**Comment by yamelsenih** [comment]
Hi @EdwinBetanc0urt where is field groups?

**Comment by EdwinBetanc0urt** [comment]
Greetings @yamelsenih, thank you for notifying us, the screenshots have been corrected.
