### ISSUE TITLE
[Bug Report] Main menu with a larger vertical separation between items

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-vue#918]
#### Steps to reproduce

1. Login

#### Screenshot or Gif（截图或动态图）
![sidebar-menu-error](https://user-images.githubusercontent.com/20288327/121791923-0a7aa780-cbbd-11eb-9786-89049e445fd0.png)

#### Expected behavior
The main menu is displayed with a vertical spacing between items larger than the correct spacing.

#### Other relevant information
* Your OS: Linux Mint 19.1 Cinnamon x64. 
* Browser: Mozilla Firefox 88.0.1.
* Node.js version: 14.17.0.
* NPM version: 7.17.0.
* adempiere-vue version: 4.3.1.

#### Additional context
This problem apparently only affects Mozilla Firefox, in Google Chrome it is displayed correctly.

**Comment by yamelsenih** [comment]
Hi @sofia-ester-calderon please can you review it
